<?php 
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class layout1{
	
	public function __construct() {
		add_action( 'admin_init', array( $this, 'team_layout_page_init' ) );
	}

	public function team_layout_page_init() {
		register_setting(
			'team_layout_option_group', // option_group
			'team_layout_option_name', // option_name
			array( $this, 'team_layout_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'team_layout_setting_section', // id
			'', // title
			array( $this, 'team_layout_section_info' ), // callback
			'team-layout-admin' // page
		);

		add_settings_field(
			'carousel_loop_0', // id
			'Carousel Loop', // title
			array( $this, 'carousel_loop_0_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'pagination_1', // id
			'Pagination', // title
			array( $this, 'pagination_1_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'navigation_2', // id
			'Navigation', // title
			array( $this, 'navigation_2_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'navigation_position_3', // id
			'Navigation Position', // title
			array( $this, 'navigation_position_3_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'autoplay_4', // id
			'Autoplay', // title
			array( $this, 'autoplay_4_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'autoplay_pause_on_hover_6', // id
			'Autoplay Pause On Hover', // title
			array( $this, 'autoplay_pause_on_hover_6_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'autoplay_timeout_7', // id
			'Autoplay Timeout', // title
			array( $this, 'autoplay_timeout_7_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'margin_8', // id
			'Margin', // title
			array( $this, 'margin_8_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'columns_in_desktop_9', // id
			'Columns in Desktop', // title
			array( $this, 'columns_in_desktop_9_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'columns_in_table_10', // id
			'Columns in Table', // title
			array( $this, 'columns_in_table_10_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'columns_in_mobile_11', // id
			'Columns in Mobile', // title
			array( $this, 'columns_in_mobile_11_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'show_team_name_12', // id
			'Show Team Name', // title
			array( $this, 'show_team_name_12_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'show_team_designation_13', // id
			'Show Team Designation', // title
			array( $this, 'show_team_designation_13_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);
		
		add_settings_field(
			'show_team_short_description', // id
			'Show Team Short Description', // title
			array( $this, 'show_team_short_description_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);
		
		add_settings_field(
			'team_short_description_limit_14', // id
			'Team Short Description Limit', // title
			array( $this, 'team_short_description_limit_14_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'show_hide_social_connection_15', // id
			'Show Social Connection', // title
			array( $this, 'show_hide_social_connection_15_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'social_link_target_16', // id
			'Social Link Target', // title
			array( $this, 'social_link_target_16_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'team_name_font_size_17', // id
			'Team Name Font Size', // title
			array( $this, 'team_name_font_size_17_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);
		add_settings_field(
			'team_name_font_weight_19', // id
			'Team Name Font Weight', // title
			array( $this, 'team_name_font_weight_19_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'hover_overlay_color_20', // id
			'Hover Overlay color', // title
			array( $this, 'hover_overlay_color_20_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);

		add_settings_field(
			'theme_color_21', // id
			'Theme Color', // title
			array( $this, 'theme_color_21_callback' ), // callback
			'team-layout-admin', // page
			'team_layout_setting_section' // section
		);
	}

	public function team_layout_sanitize($input) {
		
		$sanitary_values = array();
		if ( isset( $input['carousel_loop_0'] ) ) {
			$sanitary_values['carousel_loop_0'] = $input['carousel_loop_0'];
		}

		if ( isset( $input['pagination_1'] ) ) {
			$sanitary_values['pagination_1'] = $input['pagination_1'];
		}

		if ( isset( $input['navigation_2'] ) ) {
			$sanitary_values['navigation_2'] = $input['navigation_2'];
		}

		if ( isset( $input['navigation_position_3'] ) ) {
			$sanitary_values['navigation_position_3'] = $input['navigation_position_3'];
		}

		if ( isset( $input['autoplay_4'] ) ) {
			$sanitary_values['autoplay_4'] = $input['autoplay_4'];
		}

		if ( isset( $input['autoplay_pause_on_hover_6'] ) ) {
			$sanitary_values['autoplay_pause_on_hover_6'] = $input['autoplay_pause_on_hover_6'];
		}

		if ( isset( $input['autoplay_timeout_7'] ) ) {
			$sanitary_values['autoplay_timeout_7'] = sanitize_text_field( $input['autoplay_timeout_7'] );
		}

		if ( isset( $input['margin_8'] ) ) {
			$sanitary_values['margin_8'] = sanitize_text_field( $input['margin_8'] );
		}

		if ( isset( $input['columns_in_desktop_9'] ) ) {
			$sanitary_values['columns_in_desktop_9'] = $input['columns_in_desktop_9'];
		}

		if ( isset( $input['columns_in_table_10'] ) ) {
			$sanitary_values['columns_in_table_10'] = $input['columns_in_table_10'];
		}

		if ( isset( $input['columns_in_mobile_11'] ) ) {
			$sanitary_values['columns_in_mobile_11'] = $input['columns_in_mobile_11'];
		}

		if ( isset( $input['show_team_name_12'] ) ) {
			$sanitary_values['show_team_name_12'] = $input['show_team_name_12'];
		}

		if ( isset( $input['show_team_designation_13'] ) ) {
			$sanitary_values['show_team_designation_13'] = sanitize_text_field( $input['show_team_designation_13'] );
		}
		
		if ( isset( $input['show_team_short_description'] ) ) {
			$sanitary_values['show_team_short_description'] = sanitize_text_field( $input['show_team_short_description'] );
		}

		if ( isset( $input['team_short_description_limit_14'] ) ) {
			$sanitary_values['team_short_description_limit_14'] = sanitize_text_field( $input['team_short_description_limit_14'] );
		}

		if ( isset( $input['show_hide_social_connection_15'] ) ) {
			$sanitary_values['show_hide_social_connection_15'] = $input['show_hide_social_connection_15'];
		}

		if ( isset( $input['social_link_target_16'] ) ) {
			$sanitary_values['social_link_target_16'] = $input['social_link_target_16'];
		}

		if ( isset( $input['team_name_font_size_17'] ) ) {
			$sanitary_values['team_name_font_size_17'] = sanitize_text_field( $input['team_name_font_size_17'] );
		}

		if ( isset( $input['team_name_font_size_18'] ) ) {
			$sanitary_values['team_name_font_size_18'] = sanitize_text_field( $input['team_name_font_size_18'] );
		}

		if ( isset( $input['team_name_font_weight_19'] ) ) {
			$sanitary_values['team_name_font_weight_19'] = sanitize_text_field( $input['team_name_font_weight_19'] );
		}

		if ( isset( $input['hover_overlay_color_20'] ) ) {
			$sanitary_values['hover_overlay_color_20'] = sanitize_text_field( $input['hover_overlay_color_20'] );
		}

		if ( isset( $input['theme_color_21'] ) ) {
			$sanitary_values['theme_color_21'] = sanitize_text_field( $input['theme_color_21'] );
		}

		return $sanitary_values;
	}

	public function team_layout_section_info() {
		
	}

	public function carousel_loop_0_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?><fieldset>
		<div class="switch-field">
		<?php $checked = ( isset( $team_layout_options['carousel_loop_0'] ) && $team_layout_options['carousel_loop_0'] === 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[carousel_loop_0]" id="carousel_loop_0-0" value="true" <?php echo $checked; ?>><label for="carousel_loop_0-0">Yes</label>
		<?php $checked = ( isset( $team_layout_options['carousel_loop_0'] ) && $team_layout_options['carousel_loop_0'] === 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[carousel_loop_0]" id="carousel_loop_0-1" value="false" <?php echo $checked; ?>><label for="carousel_loop_0-1">No</label> </div></fieldset>
		<?php
	}

	public function pagination_1_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
	
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['pagination_1'] ) && $team_layout_options['pagination_1'] === 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[pagination_1]" id="pagination_1-0" value="true" <?php echo $checked; ?>><label for="pagination_1-0"> Show</label>
		<?php $checked = ( isset( $team_layout_options['pagination_1'] ) && $team_layout_options['pagination_1'] === 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[pagination_1]" id="pagination_1-1" value="false" <?php echo $checked; ?>>
		<label for="pagination_1-1"> Hide</label></div></fieldset> <?php
	}

	public function navigation_2_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['navigation_2'] ) && $team_layout_options['navigation_2'] === 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[navigation_2]" id="navigation_2-0" value="true" <?php echo $checked; ?>><label for="navigation_2-0"> Show</label>
		<?php $checked = ( isset( $team_layout_options['navigation_2'] ) && $team_layout_options['navigation_2'] === 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[navigation_2]" id="navigation_2-1" value="false" <?php echo $checked; ?>>
		<label for="navigation_2-1"> Hide</label></div></fieldset> <?php
	}

	public function navigation_position_3_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['navigation_position_3'] ) && $team_layout_options['navigation_position_3'] === 'Top Right' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[navigation_position_3]" id="navigation_position_3-0" value="Top Right" <?php echo $checked; ?>>
		<label for="navigation_position_3-0"> Top Right</label>
		<?php $checked = ( isset( $team_layout_options['navigation_position_3'] ) && $team_layout_options['navigation_position_3'] === 'Top Center' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[navigation_position_3]" id="navigation_position_3-1" value="Top Center" <?php echo $checked; ?>>
		<label for="navigation_position_3-1"> Top Center</label>
		<?php $checked = ( isset( $team_layout_options['navigation_position_3'] ) && $team_layout_options['navigation_position_3'] === 'Top Left' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[navigation_position_3]" id="navigation_position_3-2" value="Top Left" <?php echo $checked; ?>>
		<label for="navigation_position_3-2"> Top Left</label>
		<?php $checked = ( isset( $team_layout_options['navigation_position_3'] ) && $team_layout_options['navigation_position_3'] === 'Bottom Right' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[navigation_position_3]" id="navigation_position_3-3" value="Bottom Right" <?php echo $checked; ?>>
		<label for="navigation_position_3-3"> Bottom Right</label>
		<?php $checked = ( isset( $team_layout_options['navigation_position_3'] ) && $team_layout_options['navigation_position_3'] === 'Bottom Left' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[navigation_position_3]" id="navigation_position_3-4" value="Bottom Left" <?php echo $checked; ?>>
		<label for="navigation_position_3-4"> Bottom Left</label>
		<?php $checked = ( isset( $team_layout_options['navigation_position_3'] ) && $team_layout_options['navigation_position_3'] === 'Center' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[navigation_position_3]" id="navigation_position_3-5" value="Center" <?php echo $checked; ?>>
		<label for="navigation_position_3-5"> Center</label></div></fieldset> <?php
	}

	public function autoplay_4_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['autoplay_4'] ) && $team_layout_options['autoplay_4'] === 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[autoplay_4]" id="autoplay_4-0" value="true" <?php echo $checked; ?>><label for="autoplay_4-0"> Yes</label>
		<?php $checked = ( isset( $team_layout_options['autoplay_4'] ) && $team_layout_options['autoplay_4'] === 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[autoplay_4]" id="autoplay_4-1" value="false" <?php echo $checked; ?>><label for="autoplay_4-1"> No</label></div></fieldset> <?php
	}

	public function autoplay_pause_on_hover_6_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['autoplay_pause_on_hover_6'] ) && $team_layout_options['autoplay_pause_on_hover_6'] === 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[autoplay_pause_on_hover_6]" id="autoplay_pause_on_hover_6-0" value="true" <?php echo $checked; ?>>
		<label for="autoplay_pause_on_hover_6-0"> Yes</label>
		<?php $checked = ( isset( $team_layout_options['autoplay_pause_on_hover_6'] ) && $team_layout_options['autoplay_pause_on_hover_6'] === 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[autoplay_pause_on_hover_6]" id="autoplay_pause_on_hover_6-1" value="false" <?php echo $checked; ?>>
		<label for="autoplay_pause_on_hover_6-1"> No</label></div></fieldset> <?php
	}

	public function autoplay_timeout_7_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		printf(
			'<input class="medium-text" type="text" name="team_layout_option_name[autoplay_timeout_7]" id="autoplay_timeout_7" value="%s" placeholder="5000">',
			isset( $team_layout_options['autoplay_timeout_7'] ) ? esc_attr( $team_layout_options['autoplay_timeout_7']) : ''
		);
	}

	public function margin_8_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		printf(
			'<input class="medium-text" type="text" name="team_layout_option_name[margin_8]" id="margin_8" value="%s" placeholder="20"><span>px</span>',
			isset( $team_layout_options['margin_8'] ) ? esc_attr( $team_layout_options['margin_8']) : ''
		);
	}

	public function columns_in_desktop_9_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '1' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-0" value="1" <?php echo $checked; ?>>	
		<label for="columns_in_desktop_9-0"> 1</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '2' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-1" value="2" <?php echo $checked; ?>>
		<label for="columns_in_desktop_9-1"> 2</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '3' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-2" value="3" <?php echo $checked; ?>>
		<label for="columns_in_desktop_9-2"> 3</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '4' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-3" value="4" <?php echo $checked; ?>>
		<label for="columns_in_desktop_9-3"> 4</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '5' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-4" value="5" <?php echo $checked; ?>>
		<label for="columns_in_desktop_9-4"> 5</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '6' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-5" value="6" <?php echo $checked; ?>> 
		<label for="columns_in_desktop_9-5">6</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '7' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-6" value="7" <?php echo $checked; ?>>
		<label for="columns_in_desktop_9-6"> 7</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '8' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-7" value="8" <?php echo $checked; ?>>
		<label for="columns_in_desktop_9-7"> 8</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '9' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-8" value="9" <?php echo $checked; ?>>
		<label for="columns_in_desktop_9-8"> 9</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_desktop_9'] ) && $team_layout_options['columns_in_desktop_9'] === '10' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_desktop_9]" id="columns_in_desktop_9-9" value="10" <?php echo $checked; ?>>
		<label for="columns_in_desktop_9-9"> 10</label></div></fieldset> <?php
	}

	public function columns_in_table_10_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '1' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-0" value="1" <?php echo $checked; ?>>
		<label for="columns_in_table_10-0"> 1</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '2' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-1" value="2" <?php echo $checked; ?>> 
		<label for="columns_in_table_10-1">2</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '3' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-2" value="3" <?php echo $checked; ?>>
		<label for="columns_in_table_10-2"> 3</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '4' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-3" value="4" <?php echo $checked; ?>>
		<label for="columns_in_table_10-3"> 4</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '5' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-4" value="5" <?php echo $checked; ?>>
		<label for="columns_in_table_10-4"> 5</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '6' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-5" value="6" <?php echo $checked; ?>>
		<label for="columns_in_table_10-5"> 6</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '7' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-6" value="7" <?php echo $checked; ?>>
		<label for="columns_in_table_10-6"> 7</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '8' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-7" value="8" <?php echo $checked; ?>>
		<label for="columns_in_table_10-7"> 8</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '9' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-8" value="9" <?php echo $checked; ?>>
		<label for="columns_in_table_10-8"> 9</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_table_10'] ) && $team_layout_options['columns_in_table_10'] === '10' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_table_10]" id="columns_in_table_10-9" value="10" <?php echo $checked; ?>><label for="columns_in_table_10-9"> 10</label></div></fieldset> <?php
	}

	public function columns_in_mobile_11_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '1' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-0" value="1" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-0"> 1</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '2' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-1" value="2" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-1"> 2</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '3' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-2" value="3" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-2"> 3</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '4' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-3" value="4" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-3"> 4</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '5' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-4" value="5" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-4"> 5</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '6' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-5" value="6" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-5"> 6</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '7' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-6" value="7" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-6"> 7</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '8' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-7" value="8" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-7"> 8</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '9' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-8" value="9" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-8"> 9</label>
		<?php $checked = ( isset( $team_layout_options['columns_in_mobile_11'] ) && $team_layout_options['columns_in_mobile_11'] === '10' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[columns_in_mobile_11]" id="columns_in_mobile_11-9" value="10" <?php echo $checked; ?>>
		<label for="columns_in_mobile_11-9"> 10</label></div></fieldset> <?php
	}

	public function show_team_name_12_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['show_team_name_12'] ) && $team_layout_options['show_team_name_12'] === 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[show_team_name_12]" id="show_team_name_12-0" value="true" <?php echo $checked; ?>>
		<label for="show_team_name_12-0"> Yes</label>
		<?php $checked = ( isset( $team_layout_options['show_team_name_12'] ) && $team_layout_options['show_team_name_12'] === 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[show_team_name_12]" id="show_team_name_12-1" value="false" <?php echo $checked; ?>>
		<label for="show_team_name_12-1"> No</label></fieldset> </div><?php
	}

	public function show_team_designation_13_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['show_team_designation_13'] ) && $team_layout_options['show_team_designation_13'] === 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[show_team_designation_13]" id="show_team_designation_13-0" value="true" <?php echo $checked; ?>>
		<label for="show_team_designation_13-0"> Yes</label>
		<?php $checked = ( isset( $team_layout_options['show_team_designation_13'] ) && $team_layout_options['show_team_designation_13'] === 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[show_team_designation_13]" id="show_team_designation_13-1" value="false" <?php echo $checked; ?>>
		<label for="show_team_designation_13-1"> No</label></fieldset> </div><?php
		
	}
	
	public function show_team_short_description_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['show_team_short_description'] ) && $team_layout_options['show_team_short_description'] == 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[show_team_short_description]" id="show_team_short_description-0" value="true" <?php echo $checked; ?>>
		<label for="show_team_short_description-0"> Yes</label>
		<?php $checked = ( isset( $team_layout_options['show_team_short_description'] ) && $team_layout_options['show_team_short_description'] == 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[show_team_short_description]" id="show_team_short_description-1" value="false" <?php echo $checked; ?>>
		<label for="show_team_short_description-1"> No</label></fieldset> </div><?php
	}
	

	public function team_short_description_limit_14_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		printf(
			'<input class="medium-text" type="number" name="team_layout_option_name[team_short_description_limit_14]" id="team_short_description_limit_14" value="%s" placeholder="100"><span><em>words</em></span>',
			isset( $team_layout_options['team_short_description_limit_14'] ) ? esc_attr( $team_layout_options['team_short_description_limit_14']) : ''
		);
	}

	public function show_hide_social_connection_15_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <fieldset><div class="switch-field"><?php $checked = ( isset( $team_layout_options['show_hide_social_connection_15'] ) && $team_layout_options['show_hide_social_connection_15'] === 'true' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[show_hide_social_connection_15]" id="show_hide_social_connection_15-0" value="true" <?php echo $checked; ?>>
		<label for="show_hide_social_connection_15-0"> Yes</label><br>
		<?php $checked = ( isset( $team_layout_options['show_hide_social_connection_15'] ) && $team_layout_options['show_hide_social_connection_15'] === 'false' ) ? 'checked' : '' ; ?>
		<input type="radio" name="team_layout_option_name[show_hide_social_connection_15]" id="show_hide_social_connection_15-1" value="false" <?php echo $checked; ?>>
		<label for="show_hide_social_connection_15-1"> No</label></div></fieldset> <?php
	}

	public function social_link_target_16_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		?> <select name="team_layout_option_name[social_link_target_16]" id="social_link_target_16">
			<?php $selected = (isset( $team_layout_options['social_link_target_16'] ) && $team_layout_options['social_link_target_16'] === 'NewTab') ? 'selected' : '' ; ?>
			<option value="NewTab" <?php echo $selected; ?>>New Tab</option>
			<?php $selected = (isset( $team_layout_options['social_link_target_16'] ) && $team_layout_options['social_link_target_16'] === 'SameWindow') ? 'selected' : '' ; ?>
			<option value="SameWindow" <?php echo $selected; ?>>Same Window</option>
		</select> <?php
	}

	public function team_name_font_size_17_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		printf(
			'<input class="medium-text" type="number" name="team_layout_option_name[team_name_font_size_17]" id="team_name_font_size_17" value="%s" placeholder="20"><span><em>px</em></span>',
			isset( $team_layout_options['team_name_font_size_17'] ) ? esc_attr( $team_layout_options['team_name_font_size_17']) : ''
		);
	}

	public function team_name_font_weight_19_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		printf(
			'<input class="medium-text" type="number" name="team_layout_option_name[team_name_font_weight_19]" id="team_name_font_weight_19" value="%s" placeholder="600">',
			isset( $team_layout_options['team_name_font_weight_19'] ) ? esc_attr( $team_layout_options['team_name_font_weight_19']) : ''
		);
	}

	public function hover_overlay_color_20_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		printf(
			'<input class="medium-text swe_select_color color-picker" data-alpha="true" type="text"  data-default-color="rgba(0,0,0,0.75)" name="team_layout_option_name[hover_overlay_color_20]" id="hover_overlay_color_20" value="%s" >',
			isset( $team_layout_options['hover_overlay_color_20'] ) ? esc_attr( $team_layout_options['hover_overlay_color_20']) : ''
		);
	}

	public function theme_color_21_callback() {
		$team_layout_options = get_option( 'team_layout_option_name' ); 
		printf(
			'<input class="medium-text swe_select_color" type="text" name="team_layout_option_name[theme_color_21]" id="theme_color_21" value="%s">',
			isset( $team_layout_options['theme_color_21'] ) ? esc_attr( $team_layout_options['theme_color_21']) : ''
		);
	}

}

/* 
 * Retrieve this value with:
 * $team_layout_options = get_option( 'team_layout_option_name' ); // Array of All Options
 * $carousel_loop_0 = $team_layout_options['carousel_loop_0']; // Carousel Loop
 * $pagination_1 = $team_layout_options['pagination_1']; // Pagination
 * $navigation_2 = $team_layout_options['navigation_2']; // Navigation
 * $navigation_position_3 = $team_layout_options['navigation_position_3']; // Navigation Position
 * $autoplay_4 = $team_layout_options['autoplay_4']; // Autoplay
 * $pause_on_hover_5 = $team_layout_options['pause_on_hover_5']; // Pause On Hover
 * $autoplay_pause_on_hover_6 = $team_layout_options['autoplay_pause_on_hover_6']; // Autoplay Pause On Hover
 * $autoplay_timeout_7 = $team_layout_options['autoplay_timeout_7']; // Autoplay Timeout
 * $margin_8 = $team_layout_options['margin_8']; // Margin
 * $columns_in_desktop_9 = $team_layout_options['columns_in_desktop_9']; // Columns in Desktop
 * $columns_in_table_10 = $team_layout_options['columns_in_table_10']; // Columns in Table
 * $columns_in_mobile_11 = $team_layout_options['columns_in_mobile_11']; // Columns in Mobile
 * $show_team_name_12 = $team_layout_options['show_team_name_12']; // Show Team Name
 * $show_team_designation_13 = $team_layout_options['show_team_designation_13']; // Show Team Designation
 * $team_short_description_limit_14 = $team_layout_options['team_short_description_limit_14']; // Team Short Description Limit
 * $show_hide_social_connection_15 = $team_layout_options['show_hide_social_connection_15']; // Show / Hide Social Connection
 * $social_link_target_16 = $team_layout_options['social_link_target_16']; // Social Link Target
 * $team_name_font_size_17 = $team_layout_options['team_name_font_size_17']; // Team Name Font Size
 * $team_name_font_size_18 = $team_layout_options['team_name_font_size_18']; // Team Name Font Size
 * $team_name_font_weight_19 = $team_layout_options['team_name_font_weight_19']; // Team Name Font Weight
 * $hover_overlay_color_20 = $team_layout_options['hover_overlay_color_20']; // Hover Overlay color
 * $theme_color_21 = $team_layout_options['theme_color_21']; // Theme Color
 */
