<?php 
/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Teamlayout {
	
	public function __construct() {
		add_action( 'admin_menu', array( $this, 'team_layout_add_plugin_page' ) );
		require_once SWE_TEAM_MANAGEMENT_PLUGIN_DIR. '/admin/partials/layouts/class-layout1.php';
		$layout1 = new layout1();
		
	}

	public function team_layout_add_plugin_page() {
		add_submenu_page( 'edit.php?post_type=sweteammngent', __('Team setting', SWETM_TEXTDOMAIN), __('Team Layouts', SWETM_TEXTDOMAIN), 'manage_options', 'swe_team_layout_page', array($this, 'team_layout_selection_admin_page') );
	}
	public function team_layout_selection_admin_page() {
		?>
		<div class="wrap">
			<div class="inner_wrap swe_logo_controls_wraper">
				<div class="swe_team_setting_head">
					<p class="swe_team_heading_tab">Swe Team Layouts</p>
					<p>Team layout selection and their styling with shortcode listing</p>
				</div>
			<!----- Tab Starts------>
			<?php settings_errors(); ?>
			<div id="swe_team_setting_tabs" class="swe_team_tabs">
				<div class="swe_tab_links_sidebar">
				  <ul class="team_layouts_ul">
					<li><a href="#team_layouts_list">Team Carousel List</a></li>					<li><a href="#team_grid_view">Team Grid View List</a></li>					<li><a href="#setting">Setting</a></li>
					<li><a href="#faq-help">FAQ's</a></li>
				  </ul>
			    </div>
				<div class="swe_tab_content_wrap">
				
			    <!--- Layout 1--->
				 <div id="team_layouts_list">
					<h2 class="swe_layout_heading">Team layouts list, shortcodes & preview</h2>
					<div class="layout_preview">
						<?php
								include SWE_TEAM_MANAGEMENT_PLUGIN_DIR. 'admin/partials/layouts/preview/preview_layout_all.php';
							?>
					</div>
				</div>
				<!--- Layout 2--->
				 <div id="setting">
					<h2 class="swe_layout_heading">Team setting</h2>
							<form method="post" action="options.php">
								<?php
									settings_fields( 'team_layout_option_group' );
									do_settings_sections( 'team-layout-admin' );
									submit_button('Save Setting');
								?>
							</form>	
				</div>				<!--- Layout 1--->				 <div id="team_grid_view">					<h2 class="swe_layout_heading">Team Grid View list, shortcodes & preview</h2>					<div class="layout_preview">						<?php 						include SWE_TEAM_MANAGEMENT_PLUGIN_DIR. 'admin/partials/layouts/preview/preview_team_grids_all.php';						?>					</div>				</div>
				<div id="faq-help">
					<h1>FAQ's</h1>
						<div id="swe_faq_page_accordion">
						  <h3>How to Use Swe Team Management plugin</h3>
						  <div>
							<p class="use_steps">
							  Install & activate Plugin first >> Go to Swe Team Menu created in admin after pages menu.
							</p>
							<p class="use_steps">Add Team items  from Add New Team  submenu.</p>
							<p class="use_steps">After creating your teams >> go to  team layout submenu.</p>
							<p class="use_steps"> Choose the Team layouts best fits for your theme requirements from Team CarouselLists  </p>
							<p class="use_steps">Copy the shortcode like <span style="color: #000000;background: #fb880099;">[swe-team layout=1]</span> </p>
							<p class="use_steps">Paste in post/page and widgets</p>
						  </div>
						  <h3>Contact With writer</h3>
						  <div>
							<p class="swe_contact">
								Swe Team management is free team management plugin for wordpress, design and developed by <a href="http://sanjaywebexpert.com">Sanjay Sharma</a>. If is there any trouble you face during the use and plugin conflict issues or any other issues related design and development of plugin, feel free to write to us on <a href="mailto:sanjay.kumar@adaan.com">sanjay.kumar@adaan.com</a>
							</p>
						  </div>
						</div>
					</div>

				</div>
			</div><!-----End Tab Starts------>
			
			</div><!-----End Inner Wraps------>
		</div><!-----End Wraps------>
	<?php }
	
}
